// global

// apis
// data-change
export const FETCH_LISTA_DATA = 'FETCH_LISTA_DATA'
export const FETCH_LISTB_DATA = 'FETCH_LISTB_DATA'
export const FETCH_LISTC_DATA = 'FETCH_LISTC_DATA'
export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA'
export const FETCH_SELECT_DATA = 'FETCH_SELECT_DATA'
export const FETCH_SEEMORE_DATA = 'FETCH_SEEMORE_DATA'

// info-change
export const FETCH_LISTA_INFO = 'FETCH_LISTA_INFO'
export const FETCH_LISTB_INFO = 'FETCH_LISTB_INFO'
export const FETCH_LISTC_INFO = 'FETCH_LISTC_INFO'
export const FETCH_SEARCH_INFO = 'FETCH_SEARCH_INFO'
export const FETCH_SELECT_INFO = 'FETCH_SELECT_INFO'
export const FETCH_SEEMORE_INFO = 'FETCH_SEEMORE_INFO'
