// global

// apis
// data-change
export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA'
export const FETCH_LISTRA_DATA = 'FETCH_LISTRA_DATA'
export const FETCH_LISTRB_DATA = 'FETCH_LISTRB_DATA'
export const FETCH_LISTRC_DATA = 'FETCH_LISTRC_DATA'
export const FETCH_LISTRD_DATA = 'FETCH_LISTRD_DATA'
export const FETCH_KQ_LISTKA_DATA = 'FETCH_KQ_LISTKA_DATA'
export const FETCH_KQ_LISTKB_DATA = 'FETCH_KQ_LISTKB_DATA'
export const FETCH_CQ_LISTKA_DATA = 'FETCH_CQ_LISTKA_DATA'
export const FETCH_CQ_LISTKB_DATA = 'FETCH_CQ_LISTKB_DATA'
export const FETCH_LISTJA_DATA = 'FETCH_LISTJA_DATA'
export const FETCH_LISTJB_DATA = 'FETCH_LISTJB_DATA'

// info-change
export const FETCH_SEARCH_INFO = 'FETCH_SEARCH_INFO'
export const FETCH_LISTRA_INFO = 'FETCH_LISTRA_INFO'
export const FETCH_LISTRB_INFO = 'FETCH_LISTRB_INFO'
export const FETCH_LISTRC_INFO = 'FETCH_LISTRC_INFO'
export const FETCH_LISTRD_INFO = 'FETCH_LISTRD_INFO'
export const FETCH_KQ_LISTKA_INFO = 'FETCH_KQ_LISTKA_INFO'
export const FETCH_KQ_LISTKB_INFO = 'FETCH_KQ_LISTKB_INFO'
export const FETCH_CQ_LISTKA_INFO = 'FETCH_CQ_LISTKA_INFO'
export const FETCH_CQ_LISTKB_INFO = 'FETCH_CQ_LISTKB_INFO'
export const FETCH_LISTJA_INFO = 'FETCH_LISTJA_INFO'
export const FETCH_LISTJB_INFO = 'FETCH_LISTJB_INFO'
